---
# title: ACS Projects
description: Posting all code, results, and analysis for each project

# remote_theme: pmarsceill/just-the-docs
theme: just-the-docs
url: https://vereimyst.github.io/acs-projects
nav_enabled: true
heading_anchors: true
search_enabled: false
logo: "/assets/images/m-callig.jpg"
color_scheme: dark
permalink: pretty
---
