---
title: ACS Projects
description: Posting all code, results, and analysis for each project

# remote_theme: pmarsceill/just-the-docs
theme: just-the-docs
url: https://vereimyst.github.io/ACS-Projects
nav_enabled: true
heading_anchors: true
search_enabled: false
# logo: "/assets/images/m-callig.jpg"
color_scheme: dark
permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
---
